server:
  port: 8083
spring:
  application:
    name: "order"
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"
management:
  endpoints:
    web:
      exposure:
        include: "*"

rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"