spring:
  name:
    application: "product-server"
  data:
    mongodb:
      uri: mongodb://localhost:27017/product

logging:
  level:
    org:
      springframework: INFO
    com:
      example: DEBUG

server:
  port: 8081

get:
  message: 'produc product message'
